from Kaluthara_Bodhiya_A_Series import read_utube_links
from All_Playlists import waytoni_all_videos
from All_Playlists import read_utube_links_all

read_utube_links
waytoni_all_videos
read_utube_links_all