name: Update Nivan Maga Udesa Desana

on:
  push:
    paths:
      - 'NivanMagaUdesaDesana/A_series/NivanMagaUdesa_ytlinks.txt' # Nivan Maga Udesa youtube links text file
      - 'NivanMagaUdesaDesana/A_series/NivanMagaUdesa_Notes.txt' # Nivan Maga Udesa notes text file
jobs:
  run-python-script-Nivan-Maga-Udesa-Desana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python for Nivan Maga Udesa Desana
        uses: actions/setup-python@v3
        with:
          python-version: 3.11 #  Python version

      - name: Update Nivan_Maga_Udesa 
        run: python scripts/py/build_series_NivanMagaUdesa.py # Python script for Nivan Maga Udesa update
      
      - name: commit changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git commit -a -m "updated Nivan Maga Udesa Desana"
          git push

      
