name: Update MaharagamaB series Lesson Links

on:
  push:
    paths:
      - 'NivanMagaUdesaDesana/MaharagamaB/MaharagamaB_ytlinks.txt'     
      - 'NivanMagaUdesaDesana/MaharagamaB/MaharagamaB_notes.txt'     
jobs:
  run-python-script-MaharagamaAseries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11 # Set your desired Python version

      - name: Update MaharagamaB serires
        run: python scripts/gen_series_MaharagamaB.py

      - name: commit changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "updated MaharagamaB series"
            git push
          fi
