name: Update Saturday Abhidhamma Lesson Links

on:
  push:
    paths:
      - 'Saturday_Abhidhamma_Lesson/saturday_abhidhamma_lesson_youtube_links.txt' # Update with the actual path to your text file
jobs:
  run-python-script-Saturday-Lesson:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11 # Python version

      - name: Run Python Script for Saturday Abhidharma Lessons
        run: python Saturday_Abhidhamma_Lesson/read_saturday_abhidhamma_lesson_youtube_links.py

      - name: Update All_Playlists for Saturdaya Abhidharma Lesson updates
        run: python All_Playlists/read_utube_links_all.py

      - name: commit changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git commit -a -m "updated Saturday Lesson"
          git push
