name: Update Abhidhamma Aruth Desana

on:
  push:
    paths:
      - 'Abhidharma_Aruth/Abhidharma_Aruth_B_youtube_links.txt' # AA B text file
      - 'Abhidharma_Aruth/Abhidharma_Aruth_youtube_links.txt'   # AA EP text file
      - 'Abhidharma_Aruth/AA_EP_notes.txt'   # AA EP notes text file
      - 'Abhidharma_Aruth/AA_B_notes.txt'   # AA B notes text file
jobs:
  run-python-script-Abhidhamma-Aruth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11 # Python Version

      - name: Run Python Script for Abhidharma Aruth Desana
        run: python scripts/py/build_series_Abidharma_Aruth.py
      
      - name: Update All_Playlists for Abhidharma Aruth Desana updates
        run: python scripts/py/build_series_SiyaluDesana.py

      - name: commit changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git commit -a -m "updated Abhidhamma Aruth Desana"
          git push